forge/main/routes.py
from datetime import timedelta
from os import getenv, path


from flask import Blueprint, current_app, flash, redirect, render_template, request, session, url_for
from forge.acforge import get_cfn_stacks_for_region, get_forge_settings, get_nice_action_name


main = Blueprint('main', __name__, template_folder='templates')


# This checks for SAML auth and sets a session timeout
@main.before_request
def check_loggedin():
    session.permanent = True
    current_app.permanent_session_lifetime = timedelta(minutes=60)
    if getenv('NO_SAML') or current_app.config.get('NO_SAML'):
        return
    if not request.path.startswith("/saml") and not request.path.startswith("/status") and not session.get('saml'):
        login_url = url_for('login', next=request.url)
        return redirect(login_url)


# This checks for Cloudtoken credentials
@main.before_request
def check_cloudtoken():
    if 'credentials' in session and session['credentials'] is False:
        flash('No credentials - please authenticate with Cloudtoken', 'error')
        return
    return


# Helper functions
def set_action(action):
    get_forge_settings()
    session['nice_action_name'] = get_nice_action_name(action)
    session['stacks'] = sorted(get_cfn_stacks_for_region(session['region']))


# Action UI pages
@main.route('/upgrade', methods=['GET'])
def upgrade():
    set_action('upgrade')
    return render_template('upgrade.html')


@main.route('/clone', methods=['GET'])
def clone():
    set_action('clone')
    return render_template('clone.html')


@main.route('/fullrestart', methods=['GET'])
def fullrestart():
    set_action('fullrestart')
    return render_template('fullrestart.html')


@main.route('/rollingrestart', methods=['GET'])
def rollingrestart():
    set_action('rollingrestart')
    return render_template('rollingrestart.html')


@main.route('/restartnode', methods=['GET'])
def restartnode():
    set_action('restartnode')
    return render_template('restartnode.html')


@main.route('/togglenode', methods=['GET'])
def togglenode():
    set_action('togglenode')
    return render_template('togglenode.html')


@main.route('/rollingrebuild', methods=['GET'])
def rollingrebuild():
    set_action('rollingrebuild')
    return render_template('rollingrebuild.html')


@main.route('/create', methods=['GET'])
def create():
    set_action('create')
    return render_template('create.html')


@main.route('/destroy', methods=['GET'])
def destroy():
    set_action('destroy')
    return render_template('destroy.html')


@main.route('/update', methods=['GET'])
def update():
    set_action('update')
    return render_template('update.html')


@main.route('/tag', methods=['GET'])
def tag():
    set_action('tag')
    return render_template('tag.html')


@main.route('/viewlog', methods=['GET'])
def viewlog():
    set_action('viewlog')
    return render_template('viewlog.html')


@main.route('/syslog', methods=['GET'])
def syslog():
    set_action('syslog')
    return render_template('syslog.html')


@main.route('/diagnostics', methods=['GET'])
def diagnostics():
    set_action('diagnostics')
    return render_template('diagnostics.html')


@main.route('/runsql', methods=['GET'])
def runsql():
    set_action('runsql')
    return render_template('runsql.html')


@main.route('/admin', methods=['GET'])
def admin():
    set_action('admin')
    return render_template('admin.html')


@main.route('/admin/<stack_name>', methods=['GET'])
def admin_stack(stack_name):
    set_action('admin')
    return render_template('admin.html', stackToAdmin=stack_name)


@main.route('/error/<error>')
def error(error):
    return render_template('error.html', code=error), error


@main.route('/')
def index():
    get_forge_settings()
    session['nice_action_name'] = ''
    return render_template('index.html')


@main.route('/upgrade')
def upgradeSetParams():
    return render_template('upgrade.html')


@main.route('/actionreadytostart')
def actionreadytostart():
    return render_template('actionreadytostart.html')


@main.route('/actionprogress/<action>')
def actionprogress(action):
    flash(f"Action '{action}' on {request.args.get('stack')} has begun", 'success')
    return render_template('actionprogress.html')


@main.route('/setregion/<region>')
def setregion(region):
    session['region'] = region
    session['stacks'] = sorted(get_cfn_stacks_for_region(region))
    flash(f'Region selected: {region}', 'success')
    return redirect(request.referrer)


# function to get last modified time of JS files to automatically invalidate them when updated
@main.context_processor
def utility_processor():
    def get_filename_with_last_update_time(file_with_path):
        mtime = str(path.getmtime(path.join(current_app.root_path, file_with_path)))
        return f"/{file_with_path}?v={mtime}"

    return dict(get_filename_with_last_update_time=get_filename_with_last_update_time)

forge/templates/actionprogress.html
{% extends "viewlog.html" %}
{% block head %}
    {{ super() }}
    <script src="{{ get_filename_with_last_update_time('static/js/actionprogress.js') }}"></script>
{% endblock head %}

forge/templates/admin.html
{% extends "page-content.html" %}
{% block head %}
{{ super() }}
    <meta name="stackToAdmin" value={{ stackToAdmin }}>
    <script src="{{ get_filename_with_last_update_time('static/js/admin.js') }}"></script>
{% endblock head %}
    {% block descriptionPanel %}
    Allows running of various administrative actions
    {% endblock descriptionPanel %}
{% block extraInput %}
<div class="aui-panel">
    <h3>Updates</h3>
    <p>Allows you to pull changes from upstream git repositories for CloudFormation templates or Forge itself.</p>
    <div class="aui-panel">
        <a id="templateRepoSelector" href="#templateRepoDropdownDiv" aria-owns="templateRepoDropdownDiv" aria-haspopup="true"
           class="aui-button aui-style-default aui-dropdown2-trigger">
            Select Repository
        </a>

        <!-- Dropdown -->
        <div id="templateRepoDropdownDiv" class="aui-style-default aui-dropdown2"></div>
    </div>
    <div class="aui-panel">
            <button id="updateTemplatesBtn" type="submit" class="aui-button aui-button-primary update-templates update-disabled" aria-disabled="true" disabled="true">
            </button>
        </div>
</div>

<div class="aui-panel">
    <h3>Restart Forge</h3>
    <p>Restart the Forge application. This will stop any in progress actions in Forge, but will not affect any actions that are in progress in Cloudformation.</p>
    <div class="aui-panel">
        <button id="restartForgeBtn" type="submit" class="aui-button aui-button-primary">
            Restart Forge
        </button>
    </div>
</div>

<h4 class="component-heading">Stack locking</h4>
<p>Locking stacks prevents multiple actions from being performed on a stack at the same time</p>
<form class="aui">
    <fieldset class="group">
        <div class="checkbox">
            <input class="checkbox" type="checkbox" name="lockStacksCheckBox" id="lockStacksCheckBox" onclick="setStackLocking()">
            <label for="lockStacksCheckBox">Enable stack locking</label>
        </div>
    </fieldset>
</form>

<h5 class="component-heading">Currently locked stacks (multi region)</h5>
<div class="aui-panel">
    <a id="lockedStackSelector" href="#lockedStacksDropdownDiv" aria-owns="lockedStacksDropdownDiv" aria-haspopup="true"
       class="aui-button aui-style-default aui-dropdown2-trigger">
        Select Stack
    </a>

    <!-- Dropdown -->
    <div id="lockedStacksDropdownDiv" class="aui-style-default aui-dropdown2"></div>
</div>
<div class="aui-panel">
        <p id="lock-state" hidden>Action in progress: </p>
</div>
<div class="aui-panel" id="unlock-warning" hidden>
    <div class="aui-message aui-message-warning">
        <p>Only unlock if you are certain the stack is locked in error. Performing multiple actions against a stack can result in corruption.</p>
    </div>
</div>

{% endblock extraInput %}

{% block templateRepoStatusPanel %}
{#    Template Repo Status Panel    #}
<div class="aui-item">
    <section class="aui-page-notification aui-page-size-medium aui-page-panel aui-page-panel-content"  style="text-align: left">
        <h3 id="templateRepoName"></h3>
        <div id="templateRepoInformation">
            <p id="currentBranch">Current Branch: </p>
            <p id="commitsDifference">Commit Difference to Origin: </p>
            <p id="gitUpdateMessage"></p>
        </div>
    </section>
</div>
{% endblock templateRepoStatusPanel %}

{% block buttonText %}Unlock{% endblock buttonText %}

forge/templates/changeset-modal.html
{% extends "template-params.html" %}
{% block modalTitle %}Changeset Details{% endblock modalTitle %}
{% block modalContents %}
<div id="changesetWaiter">
    <p>Please wait while the changeset is generated...</p>
    <p><aui-progressbar indeterminate></aui-progressbar></p>
</div>
<div id="changesetError" class="aui-message aui-message-error">
    <p class="title">Whoops!</p>
    <p>We've encountered an error creating this changeset:</p>
    <p><code id='changesetErrorReason'></code></p>
</div>
<div id="changesetDescription">
    <p>The following changes will be made to this stack; please review and confirm you wish to proceed.</p>
    <div id='changesetDeletionWarning' class="aui-message aui-message-warning">
        <p class="title">Review this changeset carefully!</p>
        <p>This changeset includes replacement and/or deletion of some resources; proceed with caution.</p>
    </div>
    <table class="aui">
        <thead>
            <tr>
                <th id="resource-id">Id</th>
                <th id="resource-type">Type</th>
                <th id="resource-action">Action</th>
                <th id="resource-replacment">Replacement</th>
            </tr>
        </thead>
        <tbody/>
    </table>
</div>
{% endblock modalContents %}

forge/templates/create.html
{% extends "template-params.html" %}
{% block head %}
    {{ super() }}
    <script src="{{ get_filename_with_last_update_time('static/js/create.js') }}"></script>
{% endblock head %}
    {% block descriptionPanel %}
    Create new instances of Jira, Confluence or Crowd
    {% endblock descriptionPanel %}

{% block stackSelector %}
{% endblock stackSelector %}

{% block stackStatusPanel %}
{% endblock stackStatusPanel %}

{% block productSelector %}
<a id="productSelector" href="#productSelection" aria-owns="productSelection" aria-haspopup="true"
   class="aui-button aui-style-default aui-dropdown2-trigger">
    Select Product
</a>
<!-- Product dropdown -->
<div id="productSelection" class="aui-style-default aui-dropdown2">
    <ul class="aui-list-truncate">
        {% for product in session['products'] %}
        <li><a class="selectProductOption">{{ product }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock productSelector %}

{% block extraParams %}
<div class="field-group param-field-group" id="stack-name-input">
    <label for="StackNameVal" class="paramLbl">StackName</label>
    <input class="text" type="text" name="StackNameVal" id="StackNameVal" data-aui-validation-field required
           pattern="[a-zA-Z][-a-zA-Z0-9]*" data-aui-validation-pattern-msg="Stack name must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*">
</div>
{% endblock extraParams %}

{% block buttonText %}Create{% endblock buttonText %}

forge/templates/fullrestart.html
{% extends "restart.html" %}
{% block head %}
    {{ super() }}
    <script src="/static/js/restart.js"></script>
{% endblock head %}
    {% block descriptionPanel %}
    Restart all nodes in the cluster immediately. This will cause downtime to the service
    {% endblock descriptionPanel %}
{% block buttonText %}Full Restart{% endblock buttonText %}

forge/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <img src="/static/img/Atlassian-vertical-blue@2x-rgb.png">
{% endblock %}

forge/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="region" value={{ session['region'] }}>
        <meta name="stack_locking" value={{ session['stack_locking'] }}>
        <meta name="default_vpcs" value={{ session['default_vpcs'] }}>
        <meta name="default_subnets" value={{ session['default_subnets'] }}>
        <meta name="hosted_zone" value={{ session['hosted_zone'] }}>
        <meta name="ssh_key_name" value={{ session['ssh_key_name'] }}>
        {%if session['saml'] %}
        <meta name="email" value={{ session['saml']['attributes']['User.Email'][0] }}>
        <meta name="avatar_url" value={{ session['avatar_url'] }}>
        {%endif %}

        {#    AUI    #}
        <link rel="stylesheet" href="/static/aui/css/aui.min.css" media="all">
        <link rel="stylesheet" href="/static/aui/css/aui-experimental.min.css" media="all">
        <link rel="stylesheet" href="/static/aui/css/aui-iconfonts.min.css" media="all">
        <link rel="stylesheet" href="{{ get_filename_with_last_update_time('static/css/index.css') }}">

        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

        <script src="/static/jquery-3.3.1.min.js"></script>
        <script src="/static/aui/js/aui.min.js"></script>
        <script src="/static/aui/js/aui-experimental.min.js"></script>
        <script src="/static/aui/js/aui-soy.min.js"></script>
        <script src="{{ get_filename_with_last_update_time('static/js/page-content.js') }}"></script>
        <script src="{{ get_filename_with_last_update_time('static/js/utils.js') }}"></script>
        <script src="{{ get_filename_with_last_update_time('static/js/avatar.js') }}"></script>

        <title>Atlassian Cloudformation Forge</title>
        {% block head %}
        {% endblock head %}

        {%if config['ANALYTICS'] %}
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-124483963-2"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-124483963-2');
        </script>
        {%endif%}
    </head>
    <body>
            <nav class="aui-header aui-dropdown2-trigger-group" role="navigation" data-aui-responsive="true">
                <div class="aui-header-inner aui-header-primary">
                    <!-- Header -->
                    <h1 id="logo" class="aui-header-logo aui-header-logo-textonly">
                        <a href="/">
                            <span class="aui-header-logo-device">FORGE</span>
                        </a>
                    </h1>
                    <!-- Horizontal nav bar-->
                    <ul class="aui-nav">
                        {% block hnavitems %}
                        {% for region, region_name in session['regions'] %}
                        <li>
                            <a {%if session['region'] == region %}class="region-selected"{%endif%}
                               href="{{ url_for('main.setregion', region=region) }}">
                                {{ region_name }}
                            </a>
                        </li>
                        {% endfor %}
                        {% endblock %}
                    </ul>
                </div>
                {%if session['saml'] %}
                <div class="aui-header-secondary">
                    <ul class="aui-nav">
                        <li class="user-dropdown">
                            <a href="#user-nav1" aria-owns="user-nav1" aria-haspopup="true" class="aui-dropdown2-trigger aui-dropdown2-trigger">
                                <span class="aui-avatar aui-avatar-small"><img id="avatar-small" src="" /></span>
                            </a>
                            <!-- Dropdown -->
                            <div id="user-nav1" class="aui-dropdown2 aui-style-default aui-dropdown2-in-header" data-dropdown2-alignment="right">
                                <ul class="aui-list-truncate">
                                    <li><a href="{{ url_for('logout') }}">Logout</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </nav>

            <div class="aui-page-panel">
                <div class="aui-page-panel-inner">
                    <!-- Sidebar -->
                    <div class="aui-page-panel-nav">
                        <nav class="aui-navgroup aui-navgroup-vertical">
                            <div class="aui-navgroup-inner">
                                <div class="aui-nav-heading">
                                    <strong>Action Type</strong>
                                </div>
                                <ul class="aui-nav">
                                    {% block vnavitems %}
                                    <li {% if session['nice_action_name'] == 'Upgrade' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.upgrade') }}" aria-owns="aui-menu-upgrade" id="upgrade-link">Upgrade</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Full restart' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.fullrestart') }}" aria-owns="aui-menu-fullrestart" id="fullrestart-link">Full Restart</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Rolling restart' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.rollingrestart') }}" aria-owns="aui-menu-rollingrestart" id="rollingrestart-link">Rolling Restart</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Restart node' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.restartnode') }}" aria-owns="aui-menu-restartnode" id="restartnode-link">Restart Node</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Toggle node' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.togglenode') }}" aria-owns="aui-menu-togglenode" id="togglenode-link">Toggle Node Registration</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Rebuild nodes' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.rollingrebuild') }}" aria-owns="aui-menu-rollingrebuild" id="rollingrebuild-link">Rebuild Nodes</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Create stack' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.create') }}" aria-owns="aui-menu-create" id="create-link">Create</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Destroy stack' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.destroy') }}" aria-owns="aui-menu-destroy" id="destroy-link">Destroy</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Clone stack' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.clone') }}" aria-owns="aui-menu-clone" id="clone-link">Clone Stack</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Update stack' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.update') }}" aria-owns="aui-menu-update" id="update-link">Update Stack Configuration</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Tag stack' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.tag') }}" aria-owns="aui-menu-tag" id="tag-link">Tag Stack</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Diagnostics' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.diagnostics') }}" aria-owns="aui-menu-diagnostics" id="diagnostics-link">Diagnostics</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Run SQL' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.runsql') }}" aria-owns="aui-menu-runsql" id="runsql-link">Run SQL</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Stack logs' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.viewlog') }}" aria-owns="aui-menu-viewlog" id="viewlog-link">Stack Logs</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'System logs' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.syslog') }}" aria-owns="aui-menu-viewlog" id="syslog-link">System Logs</a>
                                    </li>
                                    <li {% if session['nice_action_name'] == 'Admin' %} class="aui-nav-selected" {% endif %} >
                                        <a href="{{ url_for('main.admin') }}" aria-owns="aui-menu-viewlog" id="admin-link">Admin</a>
                                    </li>
                                    {% endblock %}
                                </ul>
                            </div>
                        </nav>
                    </div>
                    <!-- Page contents-->
                    <section class="aui-page-panel-content">
                        <!--Title-->
                        <h2 class="component-heading">Atlassian Cloudformation Forge</h2>
                        {% if session['nice_action_name'] != 'Admin' %}
                        <h4 class="component-heading">{{ session['nice_action_name'] }}</h4>
                        {% endif %}
                        <!--Message bar-->
                        <div id="flash-messages">
                            {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                            {% for category, message in messages %}
                            <script>
                                displayAUIFlag('{{ message }}', '{{ category }}', "{% if category != 'error' %}auto{% endif %}");
                            </script>
                            {% endfor %}
                            {% endif %}
                            {% endwith %}
                        </div>
                        <!--Content-->
                        {% block content %}
                        {% endblock content %}
                    </section>
                </div>
            </div>
            <footer id="footer" role="contentinfo">
                <section class="footer-body">
                    <ul id="aui-footer-list">
                        <li>Copyright &#169; 2009-<script>document.write(new Date().getUTCFullYear());</script> Atlassian</li>
                        <li><a href="https://bitbucket.org/atlassian/aui/src/7.4.0/LICENSE">License</a></li>
                        <li><a href="https://bitbucket.org/atlassian/aui/src/7.4.0/changelog.md">Changelog</a></li>
                        <li><a href="/admin">Revision: {{ session['forge_version'] }}</a></li>
                    </ul>
                    <div id="footer-logo"><a href="https://www.atlassian.com/">Atlassian</a></div>
                </section>
            </footer>
        </div>
    </body>
</html>

forge/templates/page-content.html
{% extends "layout.html" %}

{% block content %}
    {#  Upgrade options  #}
    <div class="aui-group aui-group-split">
    {% block input %}

    <div class="aui-item">
        <div id="descriptionPanel" class="aui-item">
            <p>
                {% block descriptionPanel %}
                {% endblock descriptionPanel %}
            </p>
        </div>

        {% block stackSelector %}
        {#  Stack selector  #}
        <a id="stackSelector" href="#stackSelection" aria-owns="stackSelection" aria-haspopup="true"
           class="aui-button aui-style-default aui-dropdown2-trigger">
            {% block stackSelectorDescription %}
            Select Stack
            {% endblock stackSelectorDescription %}
        </a>

        <!-- Dropdown -->
        <div id="stackSelection" class="aui-style-default aui-dropdown2">
            <ul class="aui-list-truncate">
                {% for stack in session['stacks'] %}
                <li><a class="selectStackOption">{{ stack }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% endblock stackSelector %}

        {% block extraInput %}
            {% block productSelector %}
            {% endblock productSelector %}
            {% block templateSelector %}
            {% endblock templateSelector %}
            {% block nodeSelector %}
            {% endblock nodeSelector %}
            {% block extraActionsDropdown %}
            {% endblock extraActionsDropdown %}
        {% endblock extraInput %}

        {% block Parameters %}
        {% endblock Parameters %}

        {% block button %}
        {#  Button to perform page action  #}
        <div class="aui-panel">
            <button id="action-button" type="submit" class="aui-button aui-button-primary" aria-disabled="true">
                {% block buttonText %}Ok{% endblock buttonText %}
            </button>
        </div>
        {% endblock button %}
    </div>
    {% endblock input %}

    {% block stackStatusPanel %}
    {#    Current Status Panel    #}
    <div class="aui-item" id="stackPanel">
        <section class="aui-page-notification aui-page-size-medium aui-page-panel aui-page-panel-content"  style="text-align: left">
            <h3 id="stackName"></h3>
            <div id="pleaseSelectStackMsg" class="aui-page-notification-description">
                <p>Please select a stack to see it's current information</p>
            </div>
            <div id="stackInformation">
                <p id="stackState">Stack state: </p>
                <p id="serviceStatus">Service status: </p>
                <p id="currentAction">Action in progress: </p>
                <p id="currentVersion">Current version: </p>
                <h5 id="nodesHeader">Nodes: <span id="nodesCount"></span></h5>
                <p id="nodes"></p>
            </div>
        </section>
    </div>
    {% endblock stackStatusPanel %}

    {% block templateRepoStatusPanel %}
    {% endblock templateRepoStatusPanel %}


</div>

<!-- Modal prompt -->
<section id="modal-dialog" class="aui-dialog2 aui-dialog2-medium aui-layer" data-aui-modal="true" role="dialog" aria-hidden="true">
    <header class="aui-dialog2-header">
        <h2 class="aui-dialog2-header-main" id="modal-title">
            {% block modalTitle %}
            {% endblock modalTitle %}
        </h2>
        <a class="aui-dialog2-header-close">
            <span class="aui-icon aui-icon-small aui-iconfont-close-dialog">Close</span>
        </a>
    </header>
    <div class="aui-dialog2-content" id="modal-contents">
        {% block modalContents %}
        {% endblock modalContents %}
    </div>
    <footer class="aui-dialog2-footer">
        {% block modalFooterContents %}
        {% endblock modalFooterContents %}
    </footer>
</section>
{% block progress %}
{% endblock progress %}
{% endblock content%}

forge/templates/sleep.html
{% extends "page-content.html" %}
{% block head %}
    {{ super() }}
    <script src="{{ get_filename_with_last_update_time('static/js/sleep.js') }}"></script>
{% endblock head %}
    {% block descriptionPanel %}
    Sleep a stack. Note, this will spin stack down to 0 ec2 nodes, ensure rds is not multi-az, termiante any db read replica, and stop the rds.
    {% endblock descriptionPanel %}

{% block modalTitle %}Confirm sleep{% endblock modalTitle %}
{% block modalContents %}
<p>Are you sure you want to sleep <label id="stack-to-sleep"></label>?</p>
{% endblock modalContents %}

{% block buttonText %}Sleep{% endblock buttonText %}

forge/templates/togglenode.html
{% extends "page-content.html" %}
{% block head %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/togglenode.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
{% endblock head %}

{% block extraInput %}
{% block nodeSelector %}
<a id="nodeSelector" href="#nodeSelection" aria-owns="nodeSelection" aria-haspopup="true"
   class="aui-button aui-style-default aui-dropdown2-trigger">
    Select Node
</a>
<!-- Nodes dropdown -->
<div id="nodeSelection" class="aui-style-default aui-dropdown2">
    <ul class="aui-list-truncate" id="nodesList"></ul>
</div>
{% endblock nodeSelector %}
<div id="cpuChartDiv"></div>
<form class="aui">
    <fieldset class="group">
        <legend><span>Diagnostics</span></legend>
        <div class="checkbox">
            <input class="checkbox" type="checkbox" name="takeThreadDumps" id="takeThreadDumps" disabled>
            <label for="takeThreadDumps">Take thread dumps</label>
        </div>
        <div class="checkbox">
            <input class="checkbox" type="checkbox" name="takeHeapDumps" id="takeHeapDumps" disabled>
            <label for="takeHeapDumps">Take heap dumps</label>
        </div>
    </fieldset>
</form>
{% endblock extraInput %}

{% block descriptionPanel %}
Toggle the registration of the node in the load balancer. Only works for stacks that use ELBv2 load balancing.
{% endblock descriptionPanel %}

{% block buttonText %}Toggle node registration{% endblock buttonText %}

forge/templates/update.html
{% extends "changeset-modal.html" %}
{% block head %}
    {{ super() }}
    <script src="{{ get_filename_with_last_update_time('static/js/update.js') }}"></script>
{% endblock head %}

{% block buttonText %}Update{% endblock buttonText %}

forge/templates/upgrade-progress.html
{% extends "upgrade.html" %}

{% block upgradeProgress %}
        <h2>your upgrade is underway !</h2>

{% endblock %}

forge/templates/viewlog.html
{% extends "page-content.html" %}
{% block head %}
    {{ super() }}
    <script src="{{ get_filename_with_last_update_time('static/js/actionprogress.js') }}"></script>
    <script src="{{ get_filename_with_last_update_time('static/js/viewlog.js') }}"></script>
{% endblock head %}
    {% block descriptionPanel %}
    View the logs for the most recent action performed against a given stack.
    {% endblock descriptionPanel %}
{% block progress %}
<div class="aui-group">
    {#    Progress Panel    #}
    <iframe id="log" src="{{ url_for('main.actionreadytostart') }}" width="1000" height="400">
        Cannot display status because browser does not support iframes.
    </iframe>
</div>
{% endblock progress %}